### ISSUE TITLE
Feature request: middleware

### ISSUE THREAD

**Issue by mbaechtold** [Almad/django-http-digest#1]
I'd like to see a middleware so that all requests are protected.

**Comment by Almad** [comment]
Hmmm. This presents some challenges like for static, but I guess this is valid use-casel.

**Comment by mbaechtold** [comment]
Closing this issue due to its age.

**Comment by Almad** [comment]
Just when I started going back to use Django again! :D 

But yup, I think that after a decade, that's only fair

**Comment by mbaechtold** [comment]
Haha. But glad to hear that your going to use Django again 🎉
