### ISSUE TITLE
Does not successfully authenticate in Django 1.6

### ISSUE THREAD

**Issue by nan3333** [Almad/django-http-digest#2]
Using the simple method decorator authentication is not successful with the correct credentials. View is still protected via digest but does not authenticate.

Django version 1.6.2

**Comment by Almad** [comment]
Just so I know, have you tried running testsuite with it? It's located in `testproject`.

**Comment by nan3333** [comment]
Not yet. Like I said I haven't spent much time on it at all. I'll give it a
shot this evening and see what comes up

**Comment by nan3333** [comment]
Hey Lukas,

I just got around to trying to run the tests for django-http-digest but am
getting import errors from your sane testing library; not sure if that has
been updated recently either?

**Comment by Almad** [comment]
Only fair 😅
